/*
 * @Author: wdy
 * @Date: 2021-01-07 11:50:22
 * @Last Modified by: wdy
 * @Last Modified time: 2021-01-28 14:16:05
 */
const SET_BASE_HOST_URL = 'SET_BASE_HOST_URL' // 设置baseUrl
const SET_BASE_URL = 'SET_BASE_URL' // 设置baseUrl
const SET_BASE_WEBSOCKET_URL = 'SET_BASE_WEBSOCKET_URL' // 设置baseUrl

const SET_ACTIVE_WORK_AREA = 'SET_ACTIVE_WORK_AREA'
const SET_ACTIVE_CLASS = 'SET_ACTIVE_CLASS'
const SET_ACTIVE_STATION = 'SET_ACTIVE_STATION'

const SET_MENUS = 'SET_MENUS' // 设置菜单

const SET_USER_INFO = 'SET_USER_INFO'
const SET_TOKEN = 'SET_TOKEN'

const SET_IS_TOGGLE_MENU = 'SET_IS_TOGGLE_MENU'
const SET_VIEW_WIDTH = 'SET_VIEW_WIDTH'
const SET_VIEW_HEIGHT = 'SET_VIEW_HEIGHT'

export {SET_BASE_HOST_URL, SET_BASE_URL, SET_BASE_WEBSOCKET_URL, SET_MENUS, SET_ACTIVE_WORK_AREA, SET_ACTIVE_CLASS, SET_ACTIVE_STATION, SET_USER_INFO, SET_TOKEN, SET_IS_TOGGLE_MENU, SET_VIEW_WIDTH, SET_VIEW_HEIGHT}
